//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FooDo2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QFoodDBEntitiesFooDo : DbContext
    {
        public QFoodDBEntitiesFooDo()
            : base("name=QFoodDBEntitiesFooDo")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<food> foods { get; set; }
        public virtual DbSet<orderFood> orderFoods { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<table> tables { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
