//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FooDo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderFood
    {
        public int ID { get; set; }
        public int idOrder { get; set; }
        public int idFood { get; set; }
    
        public virtual food food { get; set; }
        public virtual order order { get; set; }
    }
}
