//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FooDo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table
    {
        public int ID { get; set; }
        public int positionX { get; set; }
        public int positionY { get; set; }
        public int number { get; set; }
        public int size { get; set; }
    }
}
